/**
 * Flint database schema.
 *
 * Hierarchy:
 *   user ─┬─< project_member >─ project ─┬─< environment ─┬─< api_key
 *         │                              │                └─< flag_environment_config >─ flag
 *         │                              └─< audit_log
 *         └──────< session
 *
 * Conventions:
 *  - All ids are UUIDs generated by PostgreSQL (gen_random_uuid).
 *  - All timestamps are `timestamptz`.
 *  - `updated_at` columns are maintained by the service layer, not triggers.
 *  - Audit logs are append-only: the application never UPDATEs or DELETEs rows.
 */
import {
  boolean,
  bigserial,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

/** Project membership roles, ordered from most to least privileged. */
export const projectRoleEnum = pgEnum("project_role", ["owner", "admin", "member"]);

/* -------------------------------------------------------------------------- */
/* Users & sessions                                                            */
/* -------------------------------------------------------------------------- */

export const users = pgTable(
  "users",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    /** Stored lowercase; uniqueness enforced case-insensitively. */
    email: text("email").notNull(),
    name: text("name").notNull(),
    /** Argon2id encoded hash. Never exposed outside the auth module. */
    passwordHash: text("password_hash").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [uniqueIndex("users_email_unique_idx").on(table.email)],
);

/**
 * Sessions store the SHA-256 hash of the opaque session token, never the
 * token itself. A leaked database dump therefore cannot be replayed as a
 * valid cookie.
 */
export const sessions = pgTable(
  "sessions",
  {
    /** Hex-encoded SHA-256 hash of the raw session token. */
    id: text("id").primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** Best-effort metadata for the "active sessions" view. Nullable. */
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("sessions_user_id_idx").on(table.userId)],
);

/* -------------------------------------------------------------------------- */
/* Projects & membership                                                       */
/* -------------------------------------------------------------------------- */

export const projects = pgTable(
  "projects",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    name: text("name").notNull(),
    /** URL identifier, globally unique so routes stay unambiguous. */
    slug: text("slug").notNull(),
    description: text("description"),
    createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [uniqueIndex("projects_slug_unique_idx").on(table.slug)],
);

export const projectMembers = pgTable(
  "project_members",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    role: projectRoleEnum("role").notNull().default("member"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("project_members_project_user_unique_idx").on(table.projectId, table.userId),
    index("project_members_user_id_idx").on(table.userId),
  ],
);

/* -------------------------------------------------------------------------- */
/* Environments                                                                */
/* -------------------------------------------------------------------------- */

export const environments = pgTable(
  "environments",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    /** Short identifier used in URLs and API surface, e.g. "production". */
    key: text("key").notNull(),
    name: text("name").notNull(),
    description: text("description"),
    /** Prevents accidental writes from lower environments flowing upward. */
    protected: boolean("protected").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [uniqueIndex("environments_project_key_unique_idx").on(table.projectId, table.key)],
);

/* -------------------------------------------------------------------------- */
/* Feature flags & per-environment configuration                               */
/* -------------------------------------------------------------------------- */

export const flags = pgTable(
  "flags",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    /**
     * Machine identifier, e.g. "new_checkout". Unique per project.
     * Evaluation hashes reference flag.id, so renaming a key never
     * reshuffles which users are in a rollout bucket.
     */
    key: text("key").notNull(),
    name: text("name").notNull(),
    description: text("description"),
    createdBy: uuid("created_by").references(() => users.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("flags_project_key_unique_idx").on(table.projectId, table.key),
    index("flags_project_id_idx").on(table.projectId),
  ],
);

/**
 * One row per (flag, environment). Keeping configuration here instead of on
 * the flag row makes environment isolation structural rather than logical.
 *
 * Evaluation order within an environment:
 *   1. If !enabled → false
 *   2. Targeting rules, first match wins
 *   3. Percentage rollout (deterministic bucketing)
 *   4. Default: enabled
 */
export const flagEnvironmentConfigs = pgTable(
  "flag_environment_configs",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    flagId: uuid("flag_id")
      .notNull()
      .references(() => flags.id, { onDelete: "cascade" }),
    environmentId: uuid("environment_id")
      .notNull()
      .references(() => environments.id, { onDelete: "cascade" }),
    enabled: boolean("enabled").notNull().default(false),
    /**
     * Share of users included when no targeting rule matches.
     * Stored as basis points (0–10000) to avoid floating point drift;
     * the UI presents it as a percentage.
     */
    rolloutPercentage: integer("rollout_percentage").notNull().default(10000),
    /** Ordered targeting rules. Validated by Zod before persistence. */
    rules: jsonb("rules").notNull().default([]),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("flag_env_configs_flag_env_unique_idx").on(table.flagId, table.environmentId),
    index("flag_env_configs_environment_id_idx").on(table.environmentId),
  ],
);

/* -------------------------------------------------------------------------- */
/* API keys                                                                    */
/* -------------------------------------------------------------------------- */

export const apiKeys = pgTable(
  "api_keys",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    environmentId: uuid("environment_id")
      .notNull()
      .references(() => environments.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    /**
     * Non-secret identifier embedded in the token (e.g. "flint_prod_ab12cd34")
     * so a presented key can be looked up without scanning all hashes.
     */
    displayToken: text("display_token").notNull(),
    /** Hex-encoded SHA-256 hash of the full secret. Irreversible. */
    keyHash: text("key_hash").notNull(),
    /** Throttled (at most once per hour per key) usage timestamp. */
    lastUsedAt: timestamp("last_used_at", { withTimezone: true }),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("api_keys_display_token_unique_idx").on(table.displayToken),
    uniqueIndex("api_keys_key_hash_unique_idx").on(table.keyHash),
    index("api_keys_environment_id_idx").on(table.environmentId),
  ],
);

/* -------------------------------------------------------------------------- */
/* Audit logs (append-only)                                                    */
/* -------------------------------------------------------------------------- */

/**
 * Actor identity is snapshotted (actorEmail) so history remains readable
 * even after the user account is deleted (user_id becomes NULL via
 * ON DELETE SET NULL). Rows are never updated or deleted by the app.
 */
export const auditLogs = pgTable(
  "audit_logs",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    environmentId: uuid("environment_id").references(() => environments.id, {
      onDelete: "set null",
    }),
    /** Snapshot of the environment key at log time. */
    environmentKey: text("environment_key"),
    actorUserId: uuid("actor_user_id").references(() => users.id, { onDelete: "set null" }),
    /** Snapshot of the actor email at log time. */
    actorEmail: text("actor_email"),
    /** Dot-separated event name, e.g. "flag_config.updated". */
    action: text("action").notNull(),
    resourceType: text("resource_type").notNull(),
    resourceId: text("resource_id").notNull(),
    /** Human-readable label snapshot, e.g. the flag key. */
    resourceLabel: text("resource_label"),
    /** Structured change record: { before, after } fragments. */
    changes: jsonb("changes"),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("audit_logs_project_created_idx").on(table.projectId, table.createdAt),
    index("audit_logs_resource_idx").on(table.resourceType, table.resourceId),
  ],
);

/* -------------------------------------------------------------------------- */
/* Inferred types                                                              */
/* -------------------------------------------------------------------------- */

export type User = typeof users.$inferSelect;
export type Session = typeof sessions.$inferSelect;
export type Project = typeof projects.$inferSelect;
export type ProjectMember = typeof projectMembers.$inferSelect;
export type Environment = typeof environments.$inferSelect;
export type Flag = typeof flags.$inferSelect;
export type FlagEnvironmentConfig = typeof flagEnvironmentConfigs.$inferSelect;
export type ApiKey = typeof apiKeys.$inferSelect;
export type AuditLog = typeof auditLogs.$inferSelect;
export type ProjectRole = (typeof projectRoleEnum.enumValues)[number];
